config/routes.rb
Rails.application.routes.draw do
  resources :projects
  resources :tasks
  get "/pages/:page", to: "static_pages#show", as: :page
  root "tasks#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks, dependent: :nullify

  validates :name, presence: true

  COLORS = %i( red yellow green blue indigo purple pink gray black)

  def to_s
    name
  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project, optional: true
  validates :name, presence: true

  scope :completed, -> { where(completed: true) }
  scope :not_completed, -> { where(completed: false) }
  scope :inbox, -> { where(project_id: nil)}

  def to_s
    name
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
    respond_to do |format|
      format.js { render :edit }
      format.html
    end
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to tasks_path(project_id: @project.id), notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
        format.js { redirect_to tasks_path(project_id: @project.id), status: :see_other }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
        format.js { render :edit }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to tasks_path(project_id: @project.id), notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
        format.js { redirect_to tasks_path(project_id: @project.id), status: :see_other }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
        format.js { render :edit }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
      format.js { redirect_to tasks_path, status: :see_other }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = Project.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def project_params
    params.require(:project).permit(:name, :color)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def show
    render template: "static_pages/#{params[:page]}"
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[edit update destroy show]

  # GET /tasks
  # GET /tasks.json
  def index
    @project = Project.find(params[:project_id]) if params[:project_id]
    @tasks = @project ? @project.tasks : Task
    @tasks = @tasks.order(id: :desc)
  end

  def show
    respond_to do |format|
      format.js
      format.html
    end
  end

  def new
    @task = Task.new
    @task.project_id = params[:project_id]
    respond_to do |format|
      format.js { render :edit }
      format.html
    end
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_path(project_id: @task.project_id), notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
        format.js { redirect_to tasks_path(project_id: @task.project_id), status: :see_other }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
        format.js { render :edit }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to tasks_path(project_id: @task.project_id), notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
        format.js { redirect_to tasks_path(project_id: @task.project_id), status: :see_other }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
        format.js { render :edit }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_path(project_id: @task.project_id),
        notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
      format.js { redirect_to tasks_path(project_id: @task.project_id), status: :see_other }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_task
    @task = Task.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def task_params
    params.require(:task).permit(:project_id, :name, :completed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Todoisnt
    = csrf_meta_tags
    = csp_meta_tag
    = javascript_packs_with_chunks_tag 'application' 
    /=, 'data-turbolinks-track': 'reload', defer: true
    = stylesheet_packs_with_chunks_tag 'application', media: 'all'
    /=, 'data-turbolinks-track': 'reload'
    = yield(:head)
  body
    header.container.mx-auto.mt-4
      .flex.items-center
        = link_to root_path do 
          = image_tag "logo.svg"

        = link_to "Rails version", root_path,
          class: "ml-8 #{params[:controller] == "tasks" ? "underline" : ""}"
        = link_to "React version", page_path("react"),
          data: { turbolinks: false },
          class: "ml-8 #{params[:page]=='react' ? "underline" : ""}"

    section.container.mx-auto.mt-4.flex.lg:w-1/2
      - if content_for?(:content)
        = yield(:content)
      - else
        = yield

app/views/layouts/tasks.html.slim
= content_for :content do 
  sidebar.mr-8.w-1/3
    = link_to tasks_path, class:"flex" do
      = image_tag "inbox.svg", class:"mr-2"
      . Inbox

    . data-controller="show-hide" data={ "show-hide": { "name-value": "projects-listmonitor" } }

      .flex.mt-2.cursor-pointer data={ action: "click->show-hide#toggle" }
        .mr-2
          .transition-transform.transform data-show-hide-target="chevron"
            = image_tag "chevron-r.svg" 
        . Projects
    
      ul#project_list.mt-2 data-show-hide-target="element"
        = render Project.all
    
    .mt-2 id= dom_id(Project.new)
      = render "tasks/new"
      
  section#tasks_list.w-2/3
    = yield  

= render template: "layouts/application"

app/views/projects/_form.html.slim
= form_with(model: project, class: "form") do |form|
  - if project.errors.any?
    #error_explanation
      h2
        = pluralize(project.errors.count, "error")
        |  prohibited this project from being saved:
      ul
        - project.errors.full_messages.each do |message|
          li
            = message
  .field
    = form.text_field :name, class: "w-full", placeholder: "Project name"
  .field
    = form.select :color, Project::COLORS, include_blank: true
  .actions.mt-2.flex
    .= form.button nil,
      class: "btn btn-primary block",
      data: { disable_with: "Submitting..." }
    .= link_to "Cancel", tasks_path(project_id: project.id),
      class: "btn btn-secondary block",
      data: { disable_with: "Canceling..." }
    .flex-grow
    - unless project.new_record?
      .= link_to project, method: :delete,
        class: "mr-auto block" ,
        remote: true do
        = image_tag "delete.svg"

app/views/projects/_name.html.slim
- if project.present?
  = link_to edit_project_path(project), remote: true do 
    | #{project} (#{project.tasks.not_completed.count})
- else
  | Inbox (#{Task.not_completed.count})

app/views/projects/_project.html.slim
li.flex.items-center.my-1.py-1 class="#{ @project == project ? "bg-gray-200" : "" }"
  .rounded-full.w-3.h-3.mx-1.border-black-500.border-1 class="bg-#{project.color || 'gray'}-500"
  = link_to tasks_path(project_id: project.id),
    class:"block ml-3 flex-grow" do
    | #{project} (#{project.tasks.count})

app/views/projects/edit.html.slim
h1
  | Editing Project
= render 'form', project: @project
= link_to 'Show', @project
|  | 
= link_to 'Back', projects_path

app/views/projects/edit.js.erb
document
  .getElementById('<%= dom_id(@project) %>')
  .innerHTML = "<%= j render("form", project: @project) %>"

app/views/projects/index.js.erb
document
  .getElementById('project_list')
  .innerHTML = "<%= j render(Project.all) %>";

document
  .getElementById('<%= dom_id(Project.new) %>')
  .innerHTML = "<%= j render('tasks/new')%>";

app/views/projects/new.html.slim
h1
  | New Project
= render 'form', project: @project
= link_to 'Back', projects_path

app/views/projects/show.html.slim
p#notice
  = notice
p
  strong
    | Name:
  = @project.name
= link_to 'Edit', edit_project_path(@project)
|  | 
= link_to 'Back', projects_path

app/views/static_pages/react.html.slim
- content_for :head do 
  = javascript_pack_tag 'todoisnt'
#todoisnt.w-full

app/views/static_pages/test.html.slim
h1.title
  | Heading One
  
p.mb-2 This is a paragraph of text that should be long enough to wrap. If not, we can repeat it over and over again until it does wrap. This is a paragraph of text that should be long enough to wrap. If not, we can repeat it over and over again until it does wrap. This is a paragraph of text that should be long enough to wrap. 

h2.title
  | Heading Two

p.mb-2 This is a paragraph of text that should be long enough to wrap. If not, we can repeat it over and over again until it does wrap. This is a paragraph of text that should be long enough to wrap. If not, we can repeat it over and over again until it does wrap. This is a paragraph of text that should be long enough to wrap. 

h3.title
  | Heading Three

p.mb-2 This is a paragraph of text that should be long enough to wrap. If not, we can repeat it over and over again until it does wrap. This is a paragraph of text that should be long enough to wrap. If not, we can repeat it over and over again until it does wrap. This is a paragraph of text that should be long enough to wrap. 

h4.title
  | Heading Four

p.mb-2 This is a paragraph of text that should be long enough to wrap. If not, we can repeat it over and over again until it does wrap. This is a paragraph of text that should be long enough to wrap. If not, we can repeat it over and over again until it does wrap. This is a paragraph of text that should be long enough to wrap. 

h5.title
  | Heading Five

p.mb-2 This is a paragraph of text that should be long enough to wrap. If not, we can repeat it over and over again until it does wrap. This is a paragraph of text that should be long enough to wrap. If not, we can repeat it over and over again until it does wrap. This is a paragraph of text that should be long enough to wrap. 

h6.title
  | Heading Six

p.mb-2 This is a paragraph of text that should be long enough to wrap. If not, we can repeat it over and over again until it does wrap. This is a paragraph of text that should be long enough to wrap. If not, we can repeat it over and over again until it does wrap. This is a paragraph of text that should be long enough to wrap. 

hr.my-2

p.mb-2
  em
    | This is italic text, made with em.
  i
    | This is italic text as well, made with i.

p.mb-2
  strong
    | This is bold text, made with strong.
  b
    | This is bold text as well, made with b.

p.mb-2
  u
    | This is underlined text, made with u.
  ins
    | This is inserted text, made with ins.

p.mb-2
  strike
    | This is deleted (strikethrough) text, made with strike.
  s
    | This is also strikethrough text, but made with s.
  del
    | This is deleted text, made with del.

p.mb-2
  code
    | This is computer code, made with code.
  tt
    | This is teletype text, made with tt.

p.mb-2
  kbd
    | This is text the user is supposed to enter in, or keyboard, made with kbd.
  var
    | This is a variable, made with var.
  samp
    | This is sample program output, made with samp.

p.mb-2
  small
    | This is small text, made with small.
  big
    | This is big text, made with big.

p.mb-2
  cite
    | This is a citation, made with cite.
  |  This is a 
  q
    | short quotation
  |  in the middle of a sentence, made with q. 

p.mb-2 This sentence ends with a 
  sup
    | superscript
  | . This sentence ends with a 
  sub
    | subscript
  | . 

p.mb-2 This is an abbreviation, made with abbr: 
  abbr
    | WWW
  | . This is an acronym, made with acronym: 
  acronym
    | NATO
  | . This is a term that needs a definition, made with dfn: 
  dfn
    | Yog-Sothoth
  | . 

p.mb-2 This is an unordered list: 
ul
  li
    | Koyaanisqatsi
  li
    | Powaqqatsi∫
  li
    | Naqoyqatsi

p.mb-2 This is an ordered list: 
ol
  li
    | Larry
  li
    | Moe
  li
    | Curly

p.mb-2 This is a definition list: 
dl
  dt
    | Defintion Term
  dd
    | Definition data defining the previous term
  dt
    | Another Definition Term
  dd
    | Definition data defining the previous term

p.mb-2 This is an address with breaks: 
address
  |  John Q. Public 
  br
  | 123 Main Street 
  br
  | Anywhere, ST 12345 

p.mb-2 This is a long quotation inside a blockquote: 
blockquote
  p.mb-2
    |  “I love songs about horses, railroads, land, judgement day, family, hard times, whiskey, courtship, marriage, adultery, separation, murder, war, prison, rambling, damnation, home, salvation, death, pride, humor, piety, rebellion, patriotism, larceny, determination, tragedy, rowdiness, heartbreak, and love. And Mother. And God.” ~ Johnny Cash 

p.mb-2 This is pre-formatted: 
pre
  |  Start in column one. Then indent to column ten. Then back five spaces. 

p.mb-2.mt-4 Here's a table with a border, a caption, colgroups, cols, thead, tfoot, & tbody: 

table.table
  caption.title
    | This is a table caption, made with caption

  thead
    tr
      th
        | Table Header 1
      th
        | Table Header 2
      th
        | Table Header 3
  tfoot
    tr
      td.text-sm
        | Table Footer 1
      td.text-sm
        | Table Footer 2
      td.text-sm
        | Table Footer 3
  tbody
    tr
      td
        | TD 1.1
      td
        | TD 1.2
      td
        | TD 1.3
    tr
      td
        | TD 2.1
      td
        | TD 2.2
      td
        | TD 2.3
    tr
      td
        | TD 3.1
      td
        | TD 3.2
      td
        | TD 3.3


h1.title.mt-6 Form elements

form.form
  fieldset
    legend
      | Input fields
    p.mb-4
      label[for="input__text"]
        | Text Input
      input#input__text[type="text" placeholder="Text Input"]
    p.mb-4
      label[for="input__password"]
        | Password
      input#input__password[type="password" placeholder="Type your Password"]
    p.mb-4
      label[for="input__webaddress"]
        | Web Address
      input#input__webaddress[type="url" placeholder="http://yoursite.com"]
    p.mb-4
      label[for="input__emailaddress"]
        | Email Address
      input#input__emailaddress[type="email" placeholder="name@email.com"]
    p.mb-4
      label[for="input__phone"]
        | Phone Number
      input#input__phone[type="tel" placeholder="(999) 999-9999"]
    p.mb-4
      label[for="input__search"]
        | Search
      input#input__search[type="search" placeholder="Enter Search Term"]
    p.mb-4
      label[for="input__text2"]
        | Number Input
      input#input__text2[type="number" placeholder="Enter a Number"]
    p.mb-4.error
      label.error[for="input__text3"]
        | Error
      input#input__text3.is-error[type="text" placeholder="Text Input"]
      span.block.error the error explanation
    p.mb-4.valid
      label.valid[for="input__text4"]
        | Valid
      input#input__text4.is-valid[type="text" placeholder="Text Input"]
      span.block.hint a hint


  fieldset
    legend
      | Select menus
    p.mb-4
      label[for="select"]
        | Select
      select#select
        optgroup[label="Option Group"]
          option
            | Option One
          option
            | Option Two
          option
            | Option Three


  fieldset
    legend
      | Checkboxes
    ul.list.list--bare
      li
        label[for="checkbox1"]
          input#checkbox1[name="checkbox" type="checkbox" checked="checked"]
          |  Choice A
      li
        label[for="checkbox2"]
          input#checkbox2[name="checkbox" type="checkbox"]
          |  Choice B
      li
        label[for="checkbox3"]
          input#checkbox3[name="checkbox" type="checkbox"]
          |  Choice C


  fieldset
    legend
      | Radio buttons
    ul.list.list--bare
      li
        label[for="radio1"]
          input#radio1.radio[name="radio" type="radio" checked="checked"]
          |  Option 1
      li
        label[for="radio2"]
          input#radio2.radio[name="radio" type="radio"]
          |  Option 2
      li
        label[for="radio3"]
          input#radio3.radio[name="radio" type="radio"]
          |  Option 3


  fieldset
    legend
      | Textareas
    p
      label[for="textarea"]
        | Textarea
      textarea#textarea[rows="8" cols="48" placeholder="Enter your message here"]


  fieldset
    legend
      | HTML5 inputs

    p.mb-4
      label[for="ic"]
        | Color input
      input#ic[type="color" value="#000000"]

    p.mb-4
      label[for="in"]
        | Number input
      input#in[type="number" min="0" max="10" value="5"]

    p.mb-4
      label[for="ir"]
        | Range input
      input#ir[type="range" value="10"]

    p.mb-4
      label[for="idd"]
        | Date input
      input#idd[type="date" value="1970-01-01"]

    p.mb-4
      label[for="idm"]
        | Month input
      input#idm[type="month" value="1970-01"]

    p.mb-4
      label[for="idw"]
        | Week input
      input#idw[type="week" value="1970-W01"]

    p.mb-4
      label[for="idt"]
        | Datetime input
      input#idt[type="datetime" value="1970-01-01T00:00:00Z"]

    p.mb-4
      label[for="idtl"]
        | Datetime-local input
      input#idtl[type="datetime-local" value="1970-01-01T00:00"]

  fieldset
    legend
      | Action buttons
    p.flex
      button.btn.btn-primary.mr-1
        | primary
      button.btn.btn-secundary.mr-1
        | secundary
      button.btn.btn-terciary.mr-1
        | terciary
      button.btn.btn-terciary[disabled=true]
        | disabled

app/views/tasks/_form.html.slim
= form_with(model: task, class: "form") do |form|
  = form.hidden_field :project_id 
  - if task.errors.any?
    #error_explanation
      h2
        = pluralize(task.errors.count, "error")
        |  prohibited this task from being saved:
      ul
        - task.errors.full_messages.each do |message|
          li
            = message
  .field
    = form.text_field :name, class: "w-full", placeholder: "Add a task"
  .actions.mt-2.flex
    .= form.button nil,
      class: "btn btn-primary block",
      data: { disable_with: "Submitting..." }
    - if task.new_record?
      .= link_to "Cancel", tasks_path(project_id: params[:project_id]),
        class: "btn btn-secondary block",
        data: { disable_with: "Canceling..." }      
    - else
      .= link_to "Cancel", task, remote: true,
        class: "btn btn-secondary block",
        data: { disable_with: "Canceling..." }
    .flex-grow
    - unless task.new_record?
      .= link_to task, method: :delete,
        class: "mr-auto block" ,
        remote: true do
        = image_tag "delete.svg"

app/views/tasks/_index.html.slim
h3.title id="#{dom_id(@project) if @project.present?}"
  = render('projects/name', project: @project)

ul
  - @tasks.not_completed.each do |task|
    li.border-b.border-gray-600.py-2 id=dom_id(task)
      = render task
  li.py-2.mt-4
    . id=dom_id(Task.new)
      = link_to new_task_path(project_id: @project&.id), remote: true, class: "flex" do
        = image_tag "plus.svg", class: "mr-2"
        | Add

. (data-controller="show-hide"
    data={ "show-hide": { "messages-value": ["Show completed (#{@tasks.completed.count})", "Hide completed (#{@tasks.completed.count})"],
            "name-value": "completed-tasks" } })
  .flex.my-4.text-right.cursor-pointer data={ action: "click->show-hide#toggle" }
    .transition-transform.transform data-show-hide-target="chevron"
      = image_tag "chevron-r.svg" 
    . data={ "show-hide-target": "message"} 
  ul.mt-2 data-show-hide-target="element"
    - @tasks.completed.each do |task|
      li.border-b.border-gray-600.py-2 id=dom_id(task)
        = render task

app/views/tasks/_new.html.slim
= link_to new_project_path,
  remote: true,
  class:"flex" do
  .mr-2
    = image_tag "plus.svg"
  . Create project

app/views/tasks/_task.html.slim
.flex.align-center
  = form_with(model: task) do |f|
    = f.check_box :completed, class: "mr-2 js-submit-on-click"
  = link_to edit_task_path(task),
    remote: true, class: "block flex-grow" do 
    = task

app/views/tasks/edit.html.slim
h1
  | Editing Task
= render 'form', task: @task
= link_to 'Show', @task
|  | 
= link_to 'Back', tasks_path(project_id: task.project_id)

app/views/tasks/edit.js.erb
document
  .getElementById('<%= dom_id(@task) %>')
  .innerHTML = "<%= j render("form", task: @task) %>"

app/views/tasks/index.html.slim
= render "index"

app/views/tasks/index.js.erb
document
  .getElementById('tasks_list')
  .innerHTML = "<%= j render('index') %>";

document
  .getElementById('project_list')
  .innerHTML = "<%= j render(Project.all) %>";

app/views/tasks/new.html.slim
h1
  | New Task
= render 'form', task: @task
= link_to 'Back', tasks_path(project_id: task.project_id)

app/views/tasks/show.js.erb
var el = document.getElementById('<%= dom_id(@task) %>')
<% if @task.persisted? %>
el.innerHTML = "<%= j render(@task) %>"
<% else %>
el.parentNode.removeChild(el)
<% end %>